/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Room model module.
 * @module model/Room
 * @version 1.0.0
 */
class Room {
    /**
     * Constructs a new <code>Room</code>.
     * @alias module:model/Room
     * @param rName {String} 
     * @param rFloor {Number} 
     * @param rAisle {Number} 
     * @param rEmpty {String} 
     */
    constructor(rName, rFloor, rAisle, rEmpty) { 
        
        Room.initialize(this, rName, rFloor, rAisle, rEmpty);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, rName, rFloor, rAisle, rEmpty) { 
        obj['rName'] = rName;
        obj['rFloor'] = rFloor;
        obj['rAisle'] = rAisle;
        obj['rEmpty'] = rEmpty;
    }

    /**
     * Constructs a <code>Room</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Room} obj Optional instance to populate.
     * @return {module:model/Room} The populated <code>Room</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Room();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('rName')) {
                obj['rName'] = ApiClient.convertToType(data['rName'], 'String');
            }
            if (data.hasOwnProperty('rFloor')) {
                obj['rFloor'] = ApiClient.convertToType(data['rFloor'], 'Number');
            }
            if (data.hasOwnProperty('rAisle')) {
                obj['rAisle'] = ApiClient.convertToType(data['rAisle'], 'Number');
            }
            if (data.hasOwnProperty('rEmpty')) {
                obj['rEmpty'] = ApiClient.convertToType(data['rEmpty'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Room.prototype['_id'] = undefined;

/**
 * @member {String} rName
 */
Room.prototype['rName'] = undefined;

/**
 * @member {Number} rFloor
 */
Room.prototype['rFloor'] = undefined;

/**
 * @member {Number} rAisle
 */
Room.prototype['rAisle'] = undefined;

/**
 * @member {String} rEmpty
 */
Room.prototype['rEmpty'] = undefined;






export default Room;

